apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.project_name }}-engine
  namespace: {{ .Values.global.customer_name }}
  labels:
    app: {{ .Values.global.project_name }}-engine
spec:
  selector:
    app:  {{ .Values.global.project_name }}-engine
  type: ClusterIP
  ports:
  - name: engine-listener
    protocol: TCP
    port: {{ .Values.engine.servicePort }}
    targetPort: {{ .Values.engine.containerPort }}
status: {}
