apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.novatalks.global.project_name }}-postgres
  namespace: {{ .Values.novatalks.global.customer_name }}
  labels:
    app: {{ .Values.novatalks.global.project_name }}-postgres
spec:
  replicas: {{ int .Values.novatalks.postgres.replica }}
  selector:
    matchLabels:
      app: {{ .Values.novatalks.global.project_name }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Values.novatalks.global.project_name }}-postgres
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "kubernetes.io/hostname"
                  operator: In
                  values: 
                  {{- include "getNodes" ( list $.Values.novatalks.global.nodeBind ) }}
      containers:
      - name: {{ .Values.novatalks.global.project_name }}-postgres
        image: postgres:15.3
        imagePullPolicy: "IfNotPresent"
        {{ if eq .Values.novatalks.postgres.sizing "large" }}
        args: ["-c","max_connections=300","-c","shared_buffers=256MB","-c","effective_cache_size=768MB","-c","maintenance_work_mem=64MB","-c","checkpoint_completion_target=0.9","-c","wal_buffers=7864kB","-c","default_statistics_target=100","-c","random_page_cost=1.1","-c","effective_io_concurrency=200","-c","min_wal_size=2GB","-c","max_wal_size=8GB"]
        {{ end }}
        ports:
          - containerPort: 5432
        resources:
          limits:
          {{- include "getSizingResources" ( list $.Values.novatalks.postgres.resources $.Values.novatalks.postgres.sizing ) }}
          requests:
            memory: "64Mi"
            cpu: "50m"
        envFrom:
          - configMapRef:
              name: {{ .Values.novatalks.global.project_name }}-postgres-config
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: {{ .Values.novatalks.global.project_name }}-postgresdb
            subPath: ./db/postgres
      volumes:
        - name: {{ .Values.novatalks.global.project_name }}-postgresdb
          persistentVolumeClaim:
            claimName: {{ .Values.novatalks.global.project_name }}-postgres-pvc