apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  namespace: {{ .Values.global.customer_name }}
  labels:
    app: {{ .Values.global.project_name }}-redis
  name: {{ .Values.global.project_name }}-redis
spec:
  type: ClusterIP
  ports:
  - name: redis-listener
    port: 6379
    targetPort: 6379
  selector:
    app: {{ .Values.global.project_name }}-redis
status:
  loadBalancer: {}