apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.project_name }}-postgres-config
  namespace: {{ .Values.global.customer_name }}
  labels:
    app: {{ .Values.global.project_name }}-postgres
data:
  POSTGRES_DB: {{ .Values.global.db_name }}
  POSTGRES_USER: {{ .Values.global.db_user }}
{{ .Files.Get "config/auth_core" | indent 2 }}
