apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.project_name }}-postgres
  namespace: {{ .Values.global.customer_name }}
  labels:
    app: {{ .Values.global.project_name }}-postgres
spec:
  type: ClusterIP
  ports:
   - name: {{ .Values.global.project_name }}-postgres-listener
     port: 5432
     targetPort: 5432
  selector:
   app: {{ .Values.global.project_name }}-postgres
status:
  loadBalancer: {}
