{{ $cred := $.Files.Get "_auth.yml" | fromYaml }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.project_name }}-engine-config
  namespace: {{ .Values.global.customer_name }}
  labels:
    app: {{ .Values.global.project_name }}-engine
data:
  FILE_SUPPORTED_FILE_EXTENSIONS: "{{ .Values.env.ENGINE_FILE_SUPPORTED_FILE_EXTENSIONS }}"
  UV_THREADPOOL_SIZE: "{{ .Values.env.ENGINE_UV_THREADPOOL_SIZE }}"
  NODE_ENV: "{{ .Values.env.ENGINE_NODE_ENV }}"
  APP_HOST: "{{ .Values.env.ENGINE_APP_HOST }}"
  APP_PORT: "{{ .Values.env.ENGINE_APP_PORT }}"
  FRONTEND_URL: "{{ .Values.env.ENGINE_FRONTEND_URL }}"
  WIDGET_URL: "{{ .Values.env.ENGINE_WIDGET_URL }}"
  STORE_URL: "{{ .Values.env.ENGINE_STORE_URL }}"
  SWAGGER_STATS_ENABLE: "{{ .Values.env.ENGINE_SWAGGER_STATS_ENABLE }}"
  LOG_LEVEL: "{{ .Values.env.ENGINE_LOG_LEVEL }}"
  THROTTLE_ENABLE: "{{ .Values.env.ENGINE_THROTTLE_ENABLE }}"
  THROTTLE_TTL: "{{ .Values.env.ENGINE_THROTTLE_TTL }}"
  THROTTLE_LIMIT: "{{ .Values.env.ENGINE_THROTTLE_LIMIT }}"
  MESSAGE_STATUS_INTERVAL: "{{ .Values.env.ENGINE_MESSAGE_STATUS_INTERVAL }}"
  HISTORY_REPORT_ROWS: "{{ .Values.env.ENGINE_HISTORY_REPORT_ROWS }}"
  AUTH_LOGOUT_TIMEOUT: "{{ .Values.env.ENGINE_AUTH_LOGOUT_TIMEOUT }}"
  DATABASE_DIALECT: "{{ .Values.env.ENGINE_DATABASE_DIALECT }}"
  DATABASE_HOST: "{{ .Values.env.ENGINE_DATABASE_HOST }}"
  DATABASE_PORT: "{{ .Values.env.ENGINE_DATABASE_PORT }}"
  DATABASE_USERNAME: "{{ .Values.env.ENGINE_DATABASE_USERNAME }}"
  DATABASE_NAME: "{{ .Values.env.ENGINE_DATABASE_NAME }}"
  REDIS_HOST: "{{ .Values.env.ENGINE_REDIS_HOST }}"
  REDIS_PORT: "{{ .Values.env.ENGINE_REDIS_PORT }}"
  REDIS_DB: "{{ .Values.env.ENGINE_REDIS_DB }}"
  MAIL_HOST: "{{ .Values.env.ENGINE_MAIL_HOST }}"
  MAIL_PORT: "{{ .Values.env.ENGINE_MAIL_PORT }}"
  MAIL_USER: "{{ .Values.env.ENGINE_MAIL_USER }}"
  MAIL_PASSWORD: "{{ .Values.env.ENGINE_MAIL_PASSWORD }}"
  MAIL_IGNORE_TLS: "{{ .Values.env.ENGINE_MAIL_IGNORE_TLS }}"
  MAIL_SECURE: "{{ .Values.env.ENGINE_MAIL_SECURE }}"
  MAIL_REQUIRE_TLS: "{{ .Values.env.ENGINE_MAIL_REQUIRE_TLS }}"
  MAIL_DEFAULT_EMAIL: "{{ .Values.env.ENGINE_MAIL_DEFAULT_EMAIL }}"
  MAIL_DEFAULT_NAME: "{{ .Values.env.ENGINE_MAIL_DEFAULT_NAME }}"
  MAIL_CLIENT_PORT: "{{ .Values.env.ENGINE_MAIL_CLIENT_PORT }}"
  AUTH_ACTIVE_PROVIDERS: "{{ .Values.env.ENGINE_AUTH_ACTIVE_PROVIDERS }}"
  AUTH_JWT_SECRET: "{{ .Values.env.ENGINE_AUTH_JWT_SECRET }}"
  AUTH_JWT_TOKEN_EXPIRES_IN: "{{ .Values.env.ENGINE_AUTH_JWT_TOKEN_EXPIRES_IN }}"
  PASSPORT_USERNAME_FIELD: "{{ .Values.env.ENGINE_PASSPORT_USERNAME_FIELD }}"
  PASSPORT_PASSWORD_FIELD: "{{ .Values.env.ENGINE_PASSPORT_PASSWORD_FIELD }}"
  LDAP_URL: "{{ .Values.env.ENGINE_LDAP_URL }}"
  LDAP_BIND_DN: "{{ .Values.env.ENGINE_LDAP_BIND_DN }}"
  LDAP_BIND_CREDENTIALS: "{{ .Values.env.ENGINE_LDAP_BIND_CREDENTIALS }}"
  LDAP_SEARCH_BASE: "{{ .Values.env.ENGINE_LDAP_SEARCH_BASE }}"
  LDAP_SEARCH_FILTER: "{{ .Values.env.ENGINE_LDAP_SEARCH_FILTER }}"
  LDAP_SEARCH_ATTRIBUTES: "{{ .Values.env.ENGINE_LDAP_SEARCH_ATTRIBUTES }}"
  LDAP_CA_CERTIFICATE: "{{ .Values.env.ENGINE_LDAP_CA_CERTIFICATE }}"
  LDAP_IGNORE_CERTIFICATE: "{{ .Values.env.ENGINE_LDAP_IGNORE_CERTIFICATE }}"
  # DATABASE_PASSWORD: {{ $cred.secrets.db.pass | quote }}
  # REDIS_PASSWORD: {{ $cred.secrets.redis.pass | quote }}
