# Default values for NovaTalks
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# Overrides the image tag whose default is the chart appVersion.

global:
  #Must be changed in all config below, like a db-host, redis-host
  project_name: &project_name ntk-ua-novait
  #Namespace
  customer_name: &customer_name ua-novait
  #DB Connection settings
  customer_fqdn: "novait.k3s.dev.novait.local"
  db_host: &db_host ntk-ua-novait-postgres
  db_name: &db_name ntk-ua-novait-novatalks
  db_user: &db_user ntk-ua-novait-novatalks-svc
  redis_host: &redis_host ntk-ua-novait-redis
  redis_port: &redis_port 6379
  storage: longhorn #local-path or longhorn or longhorn-migratable(with Retain data policy) - this storage class must be created
  storage_retention: Delete #longhorn only
                     #Retain - pv will be not deleted.
                     #Recycle - pv will be cleaned.
                     #Delete - pv will be deleted.
  #Helm installation will  compare only the values (nodes) and their qty. As matched nodes exists as that qty will be in affinty.
  nodeBind:
    prefered: dev-01-k3sa01d.dev.novait.local
    alter: dev-01-k3sa02d.dev.novait.local

ui:
  replica: 1
  image: apilganchuk/novatalks-ui
  tag: 2022_R2-3
  containerPort: 8000
  servicePort: 8000
  sizing: small
  resources:
    small:
      cpu: 100m
      memory: 512Mi
    medium:
      cpu: 200m
      memory: 768Mi
    large:
      cpu: 300m
      memory: 1024Mi
engine:
  replica: 1
  image: apilganchuk/novatalks-engine
  tag: 2022_R2-3
  containerPort: 3000
  servicePort: 3000
  sizing: small
  resources:
    small:
      cpu: 100m
      memory: 512Mi
    medium:
      cpu: 200m
      memory: 768Mi
    large:
      cpu: 300m
      memory: 1024Mi
botflow:
  replica: 1
  image: apilganchuk/nova-botflow
  tag: 2022_R2-4
  containerPort: 1880
  servicePort: 1880
  sizing: small
  resources:
    small:
      cpu: 150m
      memory: 512Mi
    medium:
      cpu: 200m
      memory: 768Mi
    large:
      cpu: 300m
      memory: 1024Mi
web:
  replica: 1
  image: apilganchuk/chatwoot-web-custom-prod
  tag: v2.2.0
  containerPort: 3000
  servicePort: 3000
  secretKeyBase: b1d626a9-be03-486b-a98b-de8628051e33
  frontendUrl: https://novait.k3s.dev.novait.local
  sizing: small
  resources:
    small:
      cpu: 300m
      memory: 512Mi
    medium:
      cpu: 500m
      memory: 2Gi
    large:
      cpu: 1000m
      memory: 4Gi
worker:
  replica: 1
  image: apilganchuk/chatwoot-worker-custom-prod
  tag: v2.2.0
  sizing: small
  resources:
    small:
      cpu: 100m
      memory: 384Mi
    medium:
      cpu: 200m
      memory: 512Mi
    large:
      cpu: 300m
      memory: 1024Mi
postgres: 
  sizing: small
  resources:
    small:
      cpu: 100m
      memory: 128Mi
    medium:
      cpu: 200m
      memory: 256Mi
    large:
      cpu: 300m
      memory: 512Mi
redis: 
  sizing: small
  resources:
    small:
      cpu: 50m
      memory: 128Mi
    medium:
      cpu: 100m
      memory: 256Mi
    large:
      cpu: 150m
      memory: 512Mi

env:
  ################NOVATALKS UI################
  
  UI_NOVA_CHATS_ENGINE_HOST: "http://ntk-ua-novait-engine:3000"
  UI_RUBY_HOST: "http://ntk-ua-novait-core-web:3000"
  UI_GENESYS_HOST: "https://pureconnect.demo.novait.com.ua/api/192.168.124.160"
  UI_SERVER_PORT: "8000"
  UI_SERVER_HOST: "0.0.0.0"
  UI_NODE_TLS_REJECT_UNAUTHORIZED: "0"
  UI_WIDGET_SOURCE_HOST: "https://novait.dev-01.novatalks.ai"
  UI_IMPORT_CONTACTS: "true"
  UI_LOGOUT_TIMEOUT_OFFLINE: "15000"

  ################NOVATALKS ENGINE################
  
  ENGINE_HOST: "0.0.0.0"
  ENGINE_PORT: "3000"
  ENGINE_PG_USER: *db_user
  ENGINE_PG_DB: *db_name
  ENGINE_PG_HOST: *db_host
  ENGINE_REDIS_HOST: *redis_host
  ENGINE_REDIS_PORT: *redis_port
  ENGINE_REDIS_DB: "0"
  ENGINE_RUBY_HOST: "ntk-ua-novait-core-web"
  ENGINE_RUBY_PORT: "3000"

  ################NOVA BOTFLOW################
