apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.global.project_name }}-tls-cert
  namespace: novatalks-gateways
spec:
  secretName: {{ .Values.global.project_name }}-tls-cert
  dnsNames:
  - "{{ .Values.global.customer_fqdn }}"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
