apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  namespace: {{ .Values.global.customer_name }}
  labels:
    app: {{ .Values.global.project_name }}-botflow
  name: {{ .Values.global.project_name }}-botflow
spec:
  type: ClusterIP
  ports:
  - name: botflow-listener
    port: {{ .Values.botflow.servicePort }}
    targetPort: {{ .Values.botflow.containerPort }}
  selector:
    app: {{ .Values.global.project_name }}-botflow
status:
  loadBalancer: {}
