apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.project_name }}-ui
  namespace: {{ .Values.global.customer_name }}
spec:
  selector:
    app: {{ .Values.global.project_name }}-ui
  type: ClusterIP
  ports:
  - name: ui-listener
    protocol: TCP
    port: {{ .Values.ui.servicePort }}
    targetPort: {{ .Values.ui.containerPort }}
status:
  loadBalancer: {}
