{{ $cred := $.Files.Get "config/auth.yml" | fromYaml }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.project_name }}-postgres-secret
  namespace: {{ .Values.global.customer_name }}
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.global.db_user | b64enc }}
  password: {{ $cred.secrets.db.pass | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.project_name }}-s3-secret
  namespace: {{ .Values.global.customer_name }}
type: Opaque
data:
  secretAccessKeyID: {{ $cred.secrets.objectStorage.AccessKeyID | b64enc }}
  secretAccessKey: {{ $cred.secrets.objectStorage.AccessKey | b64enc }}
  cabundle: {{ $cred.secrets.objectStorage.CA | b64enc }}