apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.global.project_name }}-postgres-secret
  namespace: {{ .Values.global.customer_name }}
spec:
  encryptedData:
    password: {{ .Values.secrets.db.pass }}
    username: {{ .Values.secrets.db.user }}
  template:
    annotations:
      sealedsecrets.bitnami.com/cluster-wide: "true"
    metadata:
      name: {{ .Values.global.project_name }}-postgres-secret
      namespace: {{ .Values.global.customer_name }}
    type: kubernetes.io/basic-auth


---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.project_name }}-s3-secret
  namespace: {{ .Values.global.customer_name }}
type: Opaque
data:
  secretAccessKeyID: {{ .Values.secrets.objectStorage.AccessKeyID | b64enc }}
  secretAccessKey: {{ .Values.secrets.objectStorage.AccessKey | b64enc }}
  cabundle: {{ .Values.secrets.objectStorage.CA | b64enc }}