apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.project_name }}-engine
  namespace: {{ .Values.global.customer_name }}
  labels:
    app: {{ .Values.global.project_name }}-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.global.project_name }}-engine
  template:
    metadata:
      labels:
        app: {{ .Values.global.project_name }}-engine
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "kubernetes.io/hostname"
                  operator: In
                  values: 
                  {{- include "getNodes" ( list $.Values.global.nodeBind ) }}
      containers:
      - name: {{ .Values.global.project_name }}-engine
        envFrom:
        - configMapRef:
            name: {{ .Values.global.project_name }}-engine-config
        image: {{ .Values.engine.image }}:{{ .Values.engine.tag }}
        imagePullPolicy: "IfNotPresent"
        resources:
          limits:
          {{- include "getSizingResources" ( list $.Values.engine.resources $.Values.engine.sizing ) }}
          requests:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: {{ int .Values.engine.containerPort }}
      restartPolicy: Always
status: {}
