apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.project_name }}-engine-config
  namespace: {{ .Values.global.customer_name }}
  labels:
    app: {{ .Values.global.project_name }}-engine
data:
  HOST: "{{ .Values.env.ENGINE_HOST }}"
  PORT: "{{ .Values.env.ENGINE_PORT }}"
  PG_USER: "{{ .Values.env.ENGINE_PG_USER }}"
  PG_DB: "{{ .Values.env.ENGINE_PG_DB }}"
  PG_HOST: "{{ .Values.env.ENGINE_PG_HOST }}"
  REDIS_PORT: "{{ .Values.env.ENGINE_REDIS_PORT }}"
  REDIS_HOST: "{{ .Values.env.ENGINE_REDIS_HOST }}"
  REDIS_DB: "{{ .Values.env.ENGINE_REDIS_DB }}"
  RUBY_HOST: "{{ .Values.env.ENGINE_RUBY_HOST }}"
  RUBY_PORT: "{{ .Values.env.ENGINE_RUBY_PORT }}"
{{ .Files.Get "config/auth_engine" | indent 2 }}
