apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.global.project_name }}-route-https
  namespace: ingress-gateways
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ .Values.global.customer_fqdn }}`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: {{ .Values.global.project_name }}-ui
      namespace: {{ .Values.global.customer_name }}
      port: {{ .Values.ui.servicePort }}
  - match: Host(`{{ .Values.global.customer_fqdn }}`) && PathPrefix(`/redbot`)
    kind: Rule
    services:
    - name: {{ .Values.global.project_name }}-botflow
      namespace: {{ .Values.global.customer_name }}
      port: {{ .Values.botflow.servicePort }}
  - match: Host(`web.{{ .Values.global.customer_fqdn }}`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: {{ .Values.global.project_name }}-core-web
      namespace: {{ .Values.global.customer_name }}
      port: {{ .Values.web.servicePort }}
  tls:
    secretName: wildcard-k3s-dev-novait-local-tls-cert
