apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.project_name }}-core-web
  namespace: {{ .Values.global.customer_name }}
spec:
  selector:
    app: {{ .Values.global.project_name }}-core-web
  type: ClusterIP
  ports:
  - name: web-listener
    protocol: TCP
    port: {{ .Values.web.servicePort }}
    targetPort: {{ .Values.web.containerPort }}
status:
  loadBalancer: {}
