novatalks:
  global:
    ver_ui: &tag_ui 2023_R2_development_f49884e5
    ver_engine: &tag_engine 2023_R2_development_0d4b3cc7
    ver_botflow: &tag_botflow 2023_R2_master_f37ce65a
    #Must be changed in all config below, like a db-host, redis-host
    project_name: &project_name ntk-dev-novait-argo
    #Namespace
    customer_name: &customer_name dev-novait-argo