novatalks:
  global:
    ver_ui: &tag_ui 2023_R2_master_e1a22404
    ver_engine: &tag_engine 2023_R2_development_0d4b3cc7
    ver_botflow: &tag_botflow 2023_R3_master_6b8ac7cf
    #Must be changed in all config below, like a db-host, redis-host
    project_name: &project_name ntk-dev-novait-argo
    #Namespace
    customer_name: &customer_name dev-novait-argo
    
  secrets:
    botflow:
      user: 
        username: "presales@novait.com.ua1"
        password: "$2b$08$2FaplJ0bd5pbrmLJL4AiMuCg8Io2.IIJF8vr3F08/hDyFsK2rWbGO1"
      admin:
        username: "support@novatalks.ai"
        password: "$2b$08$XjFM1OcVwo4xh4FrRe379eC77Li25MEOkoFMj0SQOu4VoPhcSaLFm"  
    db:
      user: AgApVZnOMq8RQ/Aa2hG9YTNmPeLFoRi13jAk6GF0/TvOt3uxXS8YGzOGAMigEDpqKJE8H5c0S0QZV8F7ic/x4nwja59vfnchSZdgsR+752mYrYcGrX7cDHhexb2yeEr8YoATFbPTblsaymXaItTlB531pE8/lIQzLbmnoBEmRiB2X8v1sEkhwGb4Hhrsq7NNb7urHCljvVLfXtCp94NF32pxU0utvMBdlKAOgZMz7jkeJo1DxkDkfivE/RqPDvglR8uASLvBDFCsGdcCI4EiTWWWNnZeG4tnNWsOwWdS7IsPIuG1iq6AA/LRQeuDQRuzLGsL2BQ6KgkpWavxUJoi60osv/etiAfyttwuRYANMiLN8pwv8P9B9HpXvXFXO5TCbxq5OfQTqgnGZMzybzpBfCkirefC7MKOznVubMNyzKhmStBtTK21FjL3C6VvkUsjlYKzZtao5bZPrxZ0o+8RBJf3SnpsARbUZeXwg4G31d9fYgqxQN0j66aKYjGCxzkgTRM4vJFvm45h+dpmoPgUBzCXqQTLCqmTmPbAd6Xr+AW8yL0Z5NeKsnLdMivjnyv2d7TkpBmZW33JPStPqgHzCraWEqqFPs0+50UM5kipXbmsqafW81QndIzZVThtW2clliQHgAnqPdmNZ7uupULsZ2YHsdmS+KcwjS/6kqk3oMFyv+wsSIFx3QyFouYRBpQogzx9C8jNzJ4B6N4jprsgLSX96bprsy5tbtmOOW4WV3vD9rU=
      pass: AgAMsAlXC3UaRTEwyeWODZ5DK776I3/7z31DaO1RXaGaanA8JLC9m3vZLphz5jo90or4UHVVWNKjH7NvrqGulyHXT72GHSNaKXS5/3ZiMuG1xp5U09EhVIY/5Kd7eaE9vScUnIUr/YrNpbE8G8rHNYyQ9WRmy6sAdwhkoNEyvurn7IPj+I7HlRDtpK6dE33iUye3dGOU9R8+xk50r5o2TpOAGuQOM5UfphKwGv9ihPOwC94c+X/rr7jlPu8CllID+kodmnDKoMaFyEfRjR3qQjAZWqpZ2ZIztXAaHQbNWTxnGSLN/cHspWGz2uzvMNyaSaDj9UDSOURLs0T7IbVkxmqFcwliWIaHzcXGufnuYIsAs/KDBZHWtZCmDuDV6UPLc57WEav4EA3QfxyCcp5yqySC2AmkpXd0XszGeItvHwwT/ko2E8R+3ctf7RFiODhdUkx5ZLOECVjJKQK9Zd6uwLLcKQSWmPG/6yvNXcFDuFpxrzPmKgfq02wX92/obeLsw0a7T87Ch90324ZV3K4jnjsrXVOgaVasDqal9CGTL70GTOMhhG8f4zZ2gjKB6+UDZrkbKiN7cJrhDUEvgK6h9cXSy6kb3qz7R2lPlumXev4e+ZoAHDX5C4TJwGL86gWlrAwagWpYu+3pYDqQIgJ1pv9n8VDlnO7ibiE5vOXyJDzC6uWf/IZiZXTKLzMorCSYuZtuWmfTbvEdNA==
    redis:
      pass: AgBQNpLHqnOC+pfUS8BCkvD1Y415Gs/JOWX2aTQxcRQ7ZEnkWKb5qLh/uih96ZfOQ16cHg0hFNpicqxscgletv9RmP9N7PwZjMUlRs+iIu7bogOFWNfUqfPqdyQ84fp+eDD7+rGqP38sI4O1x4vQEayat3cNd0QNPDJq7OW3mGkj3jZ7dMRi0e24J+WclTU9866qfIn6eumGToFZ94OWtxhY0eRXNOPagUj+6DvnEmPQlucRFih1Ft/hz5qn8w7Z2axtccbDVRvmRzEn58LSlXc5qvtZ+QZZbSjHVVYNOmUok7gDaHCXB/q6XFWQC7+MRuEGhG9fa98t5JYi/H3HoEEZdnm3jix0848t0pQvnmlPupAOJCKNk0f769Z6AEUFQ49NzbJK1Geo8GAaraFGr1HetiJH/JycQkPLounvtOgPu6TzSHK9T4trXkQy/ttJM0AZGOU6/vYoSEQ3kAOoakB3ndTdjYAF//TfjZkPkt3ScISknT+UX7kYQKJk0TfjFew+LIKjq8CH/JWKoN6M4rlnwnQOOeCz5/Hkq6IIIoz7Y9geyvpxNf12Pa595EmvZqbqRnhYLNYoSDEov1aXGJ1OiO6/jmxa2Rv9odg9WzXhbv4gamWi6+a2byJy6Ielkx5gOyKhrtD7bC12hmxn8kCeTHLvfmZ/E0ktwWPhIHQJQyCLtZ8nxS7pnJalhkEdqx4=
    objectStorage: 
      AccessKeyID: "dev-01d-lngh-backup"
      AccessKey: "AmxR5YDjgY7eqSrO5b5B9Wi2ZxTjkYXi"
      CA: |
        -----BEGIN CERTIFICATE-----
        MIIELDCCAxSgAwIBAgIBADANBgkqhkiG9w0BAQsFADBsMRcwFQYDVQQDEw5ub3Zh
        aXQtcm9vdC1jYTELMAkGA1UEBhMCVUExDTALBgNVBAgTBEt5aXYxDTALBgNVBAcT
        BEt5aXYxFDASBgNVBAoTC05vdmEgSVQgTExDMRAwDgYDVQQLEwdDb21wYW55MCAX
        DTIwMDkyMTE3MDMwMFoYDzIwNzAwOTA5MTcwMzAwWjBsMRcwFQYDVQQDEw5ub3Zh
        aXQtcm9vdC1jYTELMAkGA1UEBhMCVUExDTALBgNVBAgTBEt5aXYxDTALBgNVBAcT
        BEt5aXYxFDASBgNVBAoTC05vdmEgSVQgTExDMRAwDgYDVQQLEwdDb21wYW55MIIB
        IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3dRzNZKHf1li0mJy9SLkAUD4
        s1m8UrFW+opa+Q+j5UDe057ARwFST9kvQ9XCMMiHBIFEl9gu38mn2FboSf9KTJST
        dw99DB1mbNbQ7hCdgGUGUjPTcwxAQBySdhRsfuvqlWho5Jw9zB4/N2u8DmHQsVZH
        C8h66073uj46dAGSwgO72mYxqbUJR7GVm/h9eGvt3+vnaiAzcKO/C9dRYpzhfYqh
        +znHkm/VKmxUWUf3HpWSZOFFgWakcaLuyuNA9OWX8szFELWDdTgL1Sq4CxHZ/Zzb
        PeVMRVYEsVAwmyzjfszOexvSW/jpRxlXi1R5W5OnXLyoiOmEdhiTcy+TYWN7jwID
        AQABo4HWMIHTMB0GA1UdDgQWBBQ/9ExCFfrFV9x4Glfp92hUIVyZxDCBlgYDVR0j
        BIGOMIGLgBQ/9ExCFfrFV9x4Glfp92hUIVyZxKFwpG4wbDEXMBUGA1UEAxMObm92
        YWl0LXJvb3QtY2ExCzAJBgNVBAYTAlVBMQ0wCwYDVQQIEwRLeWl2MQ0wCwYDVQQH
        EwRLeWl2MRQwEgYDVQQKEwtOb3ZhIElUIExMQzEQMA4GA1UECxMHQ29tcGFueYIB
        ADAMBgNVHRMEBTADAQH/MAsGA1UdDwQEAwIBBjANBgkqhkiG9w0BAQsFAAOCAQEA
        XH/kcYJJ1w8Jbw1MDLRMppZ8E6NS9sa0q0l3P/XYbkJi0Jxa4d9uOO0uXQLZ6Rjr
        BUc3XmD4EK0H5YXPTg+39dETLWNgdQG9pTwgMd77tfb98ZXwfZR6QSrlD/VjaLmb
        OaL6/WLyBhcDROKu97hwtDbL79Ws14PiurwK1e4q3kB40rb2IWf6Rpgci/9WsC9m
        F4ZY1dR6m75vwPlF4YmxFgyomZodLpRNjrpLG0IEqgA/CLeuMtLSLsyQCuJXeAbl
        YBheKzECHHkhZ7oxjOoPZal+3lp0scQFwtcg/aFUEnXOh+pZ8MztVjPJ+zLOR8xE
        vEBbqW7ksuOFJwQqzXKkKQ==
        -----END CERTIFICATE-----
        -----BEGIN CERTIFICATE-----
        MIIEQTCCAymgAwIBAgIBATANBgkqhkiG9w0BAQsFADBsMRcwFQYDVQQDEw5ub3Zh
        aXQtcm9vdC1jYTELMAkGA1UEBhMCVUExDTALBgNVBAgTBEt5aXYxDTALBgNVBAcT
        BEt5aXYxFDASBgNVBAoTC05vdmEgSVQgTExDMRAwDgYDVQQLEwdDb21wYW55MCAX
        DTIwMDkyMTE3MDU0MloYDzIwNzAwOTA5MTcwNTQyWjCBgDEcMBoGA1UEAxMTbm92
        YWl0LWxvY2FsLWltZC1jYTELMAkGA1UEBhMCVUExDTALBgNVBAgTBEt5aXYxDTAL
        BgNVBAcTBEt5aXYxFDASBgNVBAoTC05vdmEgSVQgTExDMR8wHQYDVQQLExZDb3Jw
        b3JhdGUgTG9jYWwgRG9tYWluMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
        AQEA27JFxLw75Rykd50ai7Xan5+3VnHaZ/auDmATObujEsmbIrBlyMdlnFUtLW6q
        5bVJ/WLEaGnake+1O788H0EJXj5ReH7BiOHG+JPveEy3PSpBFDgbSanqlurtiS14
        hJmpv8VraVHKHJ5lJv62l/RfVCpAfH6eVixbP08DRI0i4hoPES4RNrWssiTLYvU6
        quUUo7Oo/VnS1PE/WmPjqu+5TTkkP23Z1vTrvauGCZx3tMqJiWs5inIvdPaV9+yh
        zxrR20m9GwVpKu/Fe21wc8yodAas8vit23oMyzs33FBvHf9OrIo51zFnLN58iibH
        ifyzA2apV5mFHu6dVYnRrp2z0wIDAQABo4HWMIHTMB0GA1UdDgQWBBRJFH3Vvr2L
        0PT4F5TJDufqIyf6+jCBlgYDVR0jBIGOMIGLgBQ/9ExCFfrFV9x4Glfp92hUIVyZ
        xKFwpG4wbDEXMBUGA1UEAxMObm92YWl0LXJvb3QtY2ExCzAJBgNVBAYTAlVBMQ0w
        CwYDVQQIEwRLeWl2MQ0wCwYDVQQHEwRLeWl2MRQwEgYDVQQKEwtOb3ZhIElUIExM
        QzEQMA4GA1UECxMHQ29tcGFueYIBADAMBgNVHRMEBTADAQH/MAsGA1UdDwQEAwIB
        BjANBgkqhkiG9w0BAQsFAAOCAQEAnWyZkH2Sb4trXEJra+K99Wdy9bRpiuUMSzN+
        LMVWXjiDCwbvmyA4EKDWXGSR+OmTi14YSyP7jZEWMXdXMO0i8zmlkDIagK3hCAxj
        t2sFl6SzTuhXb35lzOtGTtlGtwS4+LP5Dhrd+HcH4mRv03KGZJ+QTfDoSzDccrFC
        AjMeaIEKdClJEY+smgOSjd0ahI1DF5FdcPrO9NjHo5jt5Lr4jthu9JJiQvze7Jal
        jYyUVMM3xvAgkzJjII9hcGqOtDmoNgHYD3QR7AJLEiqcfGRjxmPmG2aSp4w5InTs
        Bdp8030GeEN5E+es3x5Z2XZi9wzGpahwNbO5El9rJZeLCTQ6ww==
        -----END CERTIFICATE-----
