novatalks:
  global:
    #Must be changed in all config below, like a db-host, redis-host
    project_name: &project_name ntk-dev-novait-argo
    #Namespace
    customer_name: &customer_name dev-novait-argo