{{ if eq .Values.global.storage "longhorn" }}

kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.global.project_name }}-pv-storage
  namespace: {{ .Values.global.customer_name }}
  labels:
    app: {{ .Values.global.project_name }}-botflow
    app: {{ .Values.global.project_name }}-redis
    app: {{ .Values.global.project_name }}-postgres
    app: {{ .Values.global.project_name }}-core-web
    app: {{ .Values.global.project_name }}-core-worker
spec:
  capacity:
    storage: 10Gi
  csi:
    driver: driver.longhorn.io
    volumeHandle: {{ .Values.global.project_name }}-novatalks-app
#    fsType: ext4
#    volumeAttributes:
#      fromBackup: ""
#      numberOfReplicas: "2"
#      fsType: ext4   
#      staleReplicaTimeout: "30"
  accessModes:
    - ReadWriteMany
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: {{ .Values.global.project_name }}-storage-pvc
    namespace: {{ .Values.global.customer_name }}
#  persistentVolumeReclaimPolicy: {{ .Values.global.storage_retention }}
  storageClassName: longhorn
  volumeMode: Filesystem

{{ end }}
