kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-migratable
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  migratable: "true"
  #share: "false"
  fromBackup: ''
  fsType: ext4
  numberOfReplicas: '2'
  staleReplicaTimeout: '30'
