apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.project_name }}-redis-config
  namespace: {{ .Values.global.customer_name }}
  labels:
    app: {{ .Values.global.project_name }}-redis
data:
  redis-config: |
    maxmemory 512mb
    maxmemory-policy allkeys-lru
    notify-keyspace-events KEA
