name: Release Charts

on:
  push:
    branches:
      - pkg-charts

jobs:
  release:
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      # - name: Prepare Release
      #   run: helm package ./novatalks_v3/ -d ./charts

      # - name: Run chart-releaser
      #   uses: helm/chart-releaser-action@v1.5.0
      #   with:
      #     charts_dir: ./charts
      #   env:
      #     CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      #     CR_SKIP_EXISTING: true
      
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: novatalks_v3
          branch: gh-pages
          target_dir: helm-charts
